# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1752ad39dddce10f47710f2af45886c73d87a9b41d826179d763d6b1c3a0e0124767b424913dc57852b68c4d070027b2cf4bf787976457dfb157f6af39d2005e

test:
  secret_key_base: d4a042a5c670004834751ab2e4bad161098f72b30e5fd986a3245d196aecfa9eb09aefdb8dec6157c0db548961d9c17da4c5930ef303053a4faa6ab22c08f6c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
